### ISSUE TITLE
14.1.3399 不能用了

### ISSUE THREAD

**Issue by zhenhappy** [STHSF/TeamViewerPersonalUseVerification#1]

**Comment by STHSF** [comment]
有报错么?我测试过是可以使用的,运行之后重新打开teamviewer,ID就改变了

**Comment by zhenhappy** [comment]
> 有报错么?我测试过是可以使用的,运行之后重新打开teamviewer,ID就改变了

没有报错, 经过我测试14.0是可以用的, 14.1.3399就失效了

**Comment by STHSF** [comment]
我试了下,确实是的,我再看看,你有什么比较好的建议?

**Comment by zhenhappy** [comment]
> 我试了下,确实是的,我再看看,你有什么比较好的建议?

我给个提示, 把"UUID"这几个字删掉就能用了
